name: Devices Readme Updater

on:
  schedule:
    - cron: '0 0 * * Sun'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo pip install PyGithub

      - name: Run Readme Generator
        run: sudo -E python3 .github/scripts/gen-devices-readme.py
